services:
  auth-service:
    build:
      context: ./user
      dockerfile: ./auth.Dockerfile
    ports:
      - "8080:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - user/.env
    depends_on:
      - postgres
      - rabbitmq

  meal-service:
    build:
      context: ./mealPlanning
      dockerfile: ./meal.Dockerfile
    ports:
      - "8081:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - mealPlanning/.env
    depends_on:
      - postgres
      - rabbitmq

  mailer-service:
    build:
      context: ./mailer
      dockerfile: ./mailer.Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - mailer/.env
    depends_on:
      - rabbitmq

  logger-service:
    build:
      context: ./logger
      dockerfile: ./logger.Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - logger/.env
    depends_on:
      - rabbitmq
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27018:27017"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/mongo/:/data/db/

  postgres:
    build:
      context: ./postgres-migrations
      dockerfile: postgres.Dockerfile
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - user/.env
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:4.0.2-management-alpine"
    ports:
      - "5674:5672"
      - "15673:15672"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/
