services:
  broker-service:
    build:
      context: ./broker
      dockerfile: ./broker.Dockerfile
    ports:
      - "8080:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - broker/.env
    depends_on:
      - rabbitmq

  listener-service:
    build:
      context: ./listener
      dockerfile: ./listener.Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - listener/.env
    depends_on:
      - rabbitmq

  auth-service:
    build:
      context: ./user
      dockerfile: ./auth.Dockerfile
    ports:
      - "8081:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - user/.env
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgres-migrations
      dockerfile: postgres.Dockerfile
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - user/.env
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:4.0.2-management-alpine"
    ports:
      - "5674:5672"
      - "15673:15672"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/
