// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: mails.proto

package mails

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SendMail_SendMail_FullMethodName = "/mails.SendMail/SendMail"
)

// SendMailClient is the client API for SendMail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendMailClient interface {
	SendMail(ctx context.Context, in *MailRequestResetLink, opts ...grpc.CallOption) (*MailResponseResetLink, error)
}

type sendMailClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMailClient(cc grpc.ClientConnInterface) SendMailClient {
	return &sendMailClient{cc}
}

func (c *sendMailClient) SendMail(ctx context.Context, in *MailRequestResetLink, opts ...grpc.CallOption) (*MailResponseResetLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailResponseResetLink)
	err := c.cc.Invoke(ctx, SendMail_SendMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMailServer is the server API for SendMail service.
// All implementations must embed UnimplementedSendMailServer
// for forward compatibility.
type SendMailServer interface {
	SendMail(context.Context, *MailRequestResetLink) (*MailResponseResetLink, error)
	mustEmbedUnimplementedSendMailServer()
}

// UnimplementedSendMailServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSendMailServer struct{}

func (UnimplementedSendMailServer) SendMail(context.Context, *MailRequestResetLink) (*MailResponseResetLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMail not implemented")
}
func (UnimplementedSendMailServer) mustEmbedUnimplementedSendMailServer() {}
func (UnimplementedSendMailServer) testEmbeddedByValue()                  {}

// UnsafeSendMailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendMailServer will
// result in compilation errors.
type UnsafeSendMailServer interface {
	mustEmbedUnimplementedSendMailServer()
}

func RegisterSendMailServer(s grpc.ServiceRegistrar, srv SendMailServer) {
	// If the following call pancis, it indicates UnimplementedSendMailServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SendMail_ServiceDesc, srv)
}

func _SendMail_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailRequestResetLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMailServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendMail_SendMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMailServer).SendMail(ctx, req.(*MailRequestResetLink))
	}
	return interceptor(ctx, in, info, handler)
}

// SendMail_ServiceDesc is the grpc.ServiceDesc for SendMail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendMail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mails.SendMail",
	HandlerType: (*SendMailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMail",
			Handler:    _SendMail_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mails.proto",
}
