POST http://localhost:8000/confirm-reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhcnNoaWFyZXphZ2hvbGkxMjEyQGdtYWlsLmNvbSIsImV4cCI6MTcyNzgyODgwN30.IxZymBqDYOZknrxQ-a5p3AdievY8s7eEdf2I7uy1aDk
content-type: application/json

{
  "password": "NewPass12",
  "confirm_password": "NewPass12"
}
