POST http://localhost:8000/api/confirm-reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhcnNoaWFyZXphZ2hvbGkxMjEyQGdtYWlsLmNvbSIsImV4cCI6MTcyNzgyOTk3Nn0.7-yQwC4Hl7AmKvPvHGTuzl_FgEmVeCJs3Tsf_fmf9wo/
content-type: application/json

{
  "password": "NewPass12",
  "confirm_password": "NewPass12"
}
