POST localhost:8081/api/protected/meals
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhcnNoaWEtcmdoIiwiZXhwIjoxNzMwMTk2NjM2fQ.LEClhffPSZEvfGNZkS4bC2o1rhVR4ctWDk2EdzEJtgI

{
  "day": "monday",
  "recipe_id": 1,
  "meal_plan_id": 1
}