POST localhost:8081/api/protected/meals
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhcnNoaWEtcmdoIiwiZXhwIjoxNzMwMjI5ODQwfQ.W3hfv9hQg16hhyesIk5zThrVntISrlYof--_S6NB_Mg

{
  "day": "monday",
  "recipe_id": 1,
  "meal_plan_id": 1
}