# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mails.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mails.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmails.proto\x12\x05mails\"D\n\x14MailRequestResetLink\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\"\'\n\x15MailResponseResetLink\x12\x0e\n\x06result\x18\x01 \x01(\t2Q\n\x08SendMail\x12\x45\n\x08SendMail\x12\x1b.mails.MailRequestResetLink\x1a\x1c.mails.MailResponseResetLinkB\x08Z\x06/mailsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mails_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006/mails'
  _globals['_MAILREQUESTRESETLINK']._serialized_start=22
  _globals['_MAILREQUESTRESETLINK']._serialized_end=90
  _globals['_MAILRESPONSERESETLINK']._serialized_start=92
  _globals['_MAILRESPONSERESETLINK']._serialized_end=131
  _globals['_SENDMAIL']._serialized_start=133
  _globals['_SENDMAIL']._serialized_end=214
# @@protoc_insertion_point(module_scope)
